# Generated by Django 4.1 on 2022-09-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dep_client', models.TextField(max_length=100)),
                ('name_client', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Num',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_dep_client', models.IntegerField()),
                ('id_project', models.PositiveIntegerField()),
            ],
        ),
    ]
