# Generated by Django 4.1 on 2022-09-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_client_options_alter_project_num_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_num',
            name='id_project',
            field=models.TextField(max_length=100, verbose_name='ID проекту'),
        ),
    ]
