# Generated by Django 4.1 on 2022-09-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_project_num_id_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_num',
            options={'ordering': ['-id_project'], 'verbose_name': 'Проект №', 'verbose_name_plural': 'Проект №'},
        ),
        migrations.AlterField(
            model_name='project_num',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project_num',
            name='id_dep_client',
            field=models.TextField(max_length=100, verbose_name='ID департаменту та клієнта'),
        ),
    ]
